name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Sync Dependencies
        run: |
          npm install
          npx cap sync android

      - name: Grant Gradlew Permission
        run: cd android && chmod +x gradlew

      - name: Build APK File
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BeatMyScore-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk